### ISSUE TITLE
Live instance respons with server error when trying to complete task in web UI

### ISSUE THREAD

**Issue by pascalwengerter** [gleam-lang/example-todomvc#24] opened 2022-12-20 22:01 UTC
Firefox 107.0.1, visiting https://gleam-todomvc.fly.dev/active, creating a task, trying to complete it (clicking the circle on the left) produces this:

<img width="625" alt="Screenshot 2022-12-20 at 23 06 24" src="https://user-images.githubusercontent.com/16822008/208775224-869ad536-9a5b-4c3b-9405-11d4c0b82114.png">

Maybe over Christmas I can find the time to take a look :)

**Comment by lpil** [comment] 2022-12-22 20:05
Oh dear!

I've been unable to reproduce this, and 502 is bad gateway, so I think this may have been an infrastructure outage with the database. I'll have to some more monitoring so we can tell more

**Comment by pascalwengerter** [comment] 2022-12-30 13:57
> Oh dear!
> 
> I've been unable to reproduce this, and 502 is bad gateway, so I think this may have been an infrastructure outage with the database. I'll have to some more monitoring so we can tell more

You're right, I've now started the server locally and can't reproduce - if it helps, I'm accessing the demo instance from Germany (Frankfurt region)...

**Comment by lpil** [comment] 2022-12-30 20:10
Thanks for verifying. I'm going to close this for now with the assumption it was an infra issue and we can reopen if it comes back

**Closed as completed by lpil** 2022-12-30 20:10 UTC

**Comment by pascalwengerter** [comment] 2022-12-30 20:14
> Thanks for verifying. I'm going to close this for now with the assumption it was an infra issue and we can reopen if it comes back

It was an infrastructure issue still few days ago, but sure :) no worries
